### ISSUE TITLE
Tetris mist maar @michiel2005 wilt het niet fixen

### ISSUE THREAD

**Issue by Flawake** [ChrisDo28/Mini-Christof#1]
Als ik op de webpagina ga kijken zie ik verschijdene tabjes zoals Home Foto's en Links.
Tot mijn diepste teleurstelling zie ik daar helaas geen tabje Tetris :(

**Comment by ChrisDo28** [comment]
Hi beste @michiel2005,

Ik snap dat je het kopje Tetris mist.
Maar de site is niet gericht op games dus ook niet op tetris.
Maar mischien kan je het op je eigen website maken maar niet getreurd er komt mischien in de toekomst wel games op de website.

Groet van Christof(@ChrisDo28 )

**Comment by Flawake** [comment]
Flappybird dan? :)

**Comment by ChrisDo28** [comment]
dat valt onder games

groet van christof (@ChrisDo28 )

**Comment by michiel2005** [comment]
#:(

**Comment by ChrisDo28** [comment]
@michiel2005 je mag je kopje je maken maar dan ook met inhoud maar wel met de naam GAmes

**Comment by ChrisDo28** [comment]
I add the games page you can add the game on the page

**Comment by ChrisDo28** [comment]
het is opgelost
